x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
2021-02-05 16:42:22.610562: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-05 16:42:22.610902: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-05 16:42:22.610922: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-05 16:42:22.610954: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (I-Wolf): /proc/driver/nvidia/version does not exist
2021-02-05 16:42:22.611320: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-05 16:42:22.611552: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-05 16:42:27.701984: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2021-02-05 16:42:27.702041: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2021-02-05 16:42:27.702993: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2021-02-05 16:42:29.084866: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 614400000 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "/home/wolf/MyCode/HPC/ml_assignment/cifar10_hvd_2.py", line 98, in <module>
    model.fit(x_train, y_train,
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 119, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1068, in fit
    callbacks = callbacks_module.CallbackList(
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 231, in __init__
    self.set_model(model)
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 286, in set_model
    callback.set_model(model)
TypeError: set_model() missing 1 required positional argument: 'model'
